-- Disable Row Level Security on all tables for development
-- Run this in Supabase SQL Editor

ALTER TABLE IF EXISTS resources DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS jobs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS magnet_interaction_rules DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS drop_rules DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS job_row_configs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS truck_driver_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS employees DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS equipment DISABLE ROW LEVEL SECURITY;