name: Unit Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint (no warnings)
        run: npm run lint:check

      - name: Typecheck
        run: npm run typecheck

      - name: Create test env
        run: |
          echo "VITE_SUPABASE_URL=${{ secrets.VITE_SUPABASE_URL }}" >> .env
          echo "VITE_SUPABASE_ANON_KEY=${{ secrets.VITE_SUPABASE_ANON_KEY }}" >> .env
        shell: bash

      - name: Run unit tests
        run: npm test -- --run --reporter=dot

      - name: Upload junit report (if available)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vitest-report
          path: |
            junit.xml
            coverage
          if-no-files-found: ignore

